export const teamOptions = [
	{ name: 'Red', color: 'bg-red-500' },
	{ name: 'Orange', color: 'bg-orange-500' },
	{ name: 'Amber', color: 'bg-amber-500' },
	{ name: 'Yellow', color: 'bg-yellow-500' },
	{ name: 'Lime', color: 'bg-lime-500' },
	{ name: 'Green', color: 'bg-green-500' },
	{ name: 'Emerald', color: 'bg-emerald-500' },
	{ name: 'Teal', color: 'bg-teal-500' },
	{ name: 'Cyan', color: 'bg-cyan-500' },
	{ name: 'Sky', color: 'bg-sky-500' },
	{ name: 'Blue', color: 'bg-blue-500' },
	{ name: 'Indigo', color: 'bg-indigo-500' },
	{ name: 'Violet', color: 'bg-violet-500' },
	{ name: 'Purple', color: 'bg-purple-500' },
	{ name: 'Fuchsia', color: 'bg-fuchsia-500' },
	{ name: 'Pink', color: 'bg-pink-500' },
	{ name: 'Rose', color: 'bg-rose-500' },
];
