export const teamOptions = [
	{ name: 'Red', color: 'bg-Red-500' },
	{ name: 'Orange', color: 'bg-Orange-500' },
	{ name: 'Amber', color: 'bg-Amber-500' },
	{ name: 'Yellow', color: 'bg-Yellow-500' },
	{ name: 'Lime', color: 'bg-Lime-500' },
	{ name: 'Green', color: 'bg-Green-500' },
	{ name: 'Emerald', color: 'bg-Emerald-500' },
	{ name: 'Teal', color: 'bg-Teal-500' },
	{ name: 'Cyan', color: 'bg-Cyan-500' },
	{ name: 'Sky', color: 'bg-Sky-500' },
	{ name: 'Blue', color: 'bg-Blue-500' },
	{ name: 'Indigo', color: 'bg-Indigo-500' },
	{ name: 'Violet', color: 'bg-Violet-500' },
	{ name: 'Purple', color: 'bg-Purple-500' },
	{ name: 'Fuchsia', color: 'bg-Fuchsia-500' },
	{ name: 'Pink', color: 'bg-Pink-500' },
	{ name: 'Rose', color: 'bg-Rose-500' },
];
