name: clean-up-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request DELETE \
          --url 'https://teams.gad.engineer/api/cron/cleanUp'
