name: clean-up-15-minute-cron
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request DELETE \
          --url 'https://teams.gad.engineer/api/cron/cleanUp'